autoload -U compinit
compinit
_comp_options+=(globdots)
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'

# Don't have the shell check for mail
unset MAIL

# Get other shell configuration
export ZSH_PATH=$HOME/.config/zsh
source $ZSH_PATH/zsh.prompt       # set the prompt
source $ZSH_PATH/zsh.path         # setup the PATH
source $ZSH_PATH/zsh.manpath      # setup the MANPATH
source $ZSH_PATH/zsh.aliases      # setup command aliases

bindkey -v
export KEYTIMEOUT=1

umask 077

# Turn off core dumps
limit coredumpsize 0

# Set some usefull options
setopt nohup            # Don't kill jobs when the shell exits
setopt nobeep           # Don't beep at me all the time
setopt nocheckjobs      # Don't check for running jobs at shell exit
setopt longlistjobs     # Show more information about jobs
setopt pushdtohome      # pushd goes to $HOME if nothing else is given
setopt noflowcontrol    # Disables ^S/^Q in line-edit mode

export PATH="/usr/local/sbin:$PATH"
